server:
  port: 8186
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://ec2-54-172-173-58.compute-1.amazonaws.com:5432/decffacf69dsah
    username: ouiuyxspmhinlw
    password: b515b4a35a18b1d548424a1d934c85963433e10cfbbcf46f76319c4a050b5057
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        default_schema: customers
  jackson:
  serialization:
    indent_output: true
jwt:
  secret: topsecretkey123rieubherotuh3498th398gh395g8h598gh4g8gidufghdifughi43gg4334t3h4gi34uhgi35uhgi35ughi45ugho98dhf98bhg
